import { crowd } from '../public/shared/personas.js';
const p = crowd('zh')[0];
console.log(JSON.stringify(p, null, 2));
const people = crowd('zh');
console.log('\ncity 前 6 个：', people.slice(0, 6).map((w) => w.city).join(' | '));
console.log('不同 city 数：', new Set(people.map((w) => w.city)).size);
console.log('不同 job 数：', new Set(people.map((w) => w.job)).size);
console.log('不同 age 数：', new Set(people.map((w) => w.age)).size);
console.log('age 样例：', [...new Set(people.map((w) => w.age))].slice(0, 8).join(' | '));
console.log('interests 长度分布：', [...new Set(people.map((w) => w.interests.length))].sort().join(','));
console.log('兴趣总数：', new Set(people.flatMap((w) => w.interests)).size);
console.log('temper：', [...new Set(people.map((w) => w.temper))].join(' | '));
